### PR TITLE
Supporting memory-copy-based serialization of matrices

### PR DESCRIPTION
**Pull request by BrunoBozza**
This adds support for generic, memory-copy-based serialization of matrices and higher rank arrays. Other than the update to zero-object replication by Jin on tasks.fs, it's all contained to generic serialization code.

### CODE REVIEW

**Comment by zhuweirong** [comment]
Squash the two commits into one?

**Comment by BrunoBozza** [comment]
Squashed! Had to tell git what to rebase: "git rebase HEAD~1" worked.

**Comment by zhuweirong** [comment]
It seems there are 5 commits now  ..... the rebase is also rewriting history of some other existing commits.  In this case, it might be easier to just do a  "git reset upstream/master"  (assume "upstream" refers to MSRCCS/master), then do a force push. It will appear as a single commit.

**Comment by BrunoBozza** [comment]
Ok. Single commit now. Hadn't seen the mess that the rebase made.

**Pull request merged**
