### PR TITLE
Thread pool

### PR DESCRIPTION
**Pull request by jinlmsft**
Rewrite Threadpool. Add additional support to trace bugs in Mono.

### CODE REVIEW

**Comment by dsyme** [comment]
Any idea what's up with the Travis build? 

Best
don

**Comment by msrccsbuild** [comment]
It seems that paket breaks, which causes Travis build to fail. More specifically, Paket fails to pull down the following NuGet packages FSharpVSPowerTools.Core 2.3.0, and Octokit 0.18.0, which causes Travis build to fails.

Interestingly, the package gets successfully pulled during windows build, but fails in Linux build (I have verified that the pull fails in a Linux machine).

I assume that this should affect other Paket/Scaffold users, and are waiting for a fix from Paket/FSharpVSPoweTools/Octokit. I don't know who to report this issue.

Best,
Jin

**Comment by dsyme** [comment]
I suppose report it to https://github.com/fsprojects/Paket if you think it's paket.

**Comment by jinlmsft** [comment]
I am not sure what is the root cause. It can be either: 1) Paket, 2) FSharpVSPoweTools/Octokit. 

Jin

**Pull request merged**
